/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xonda' at '7/17/16 8:04 PM' with Gradle 2.6
 *
 * @author xonda, @date 7/17/16 8:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
